### ISSUE TITLE
CSS changes to address ecma262 issue #956

### ISSUE THREAD

**Issue by tjcrowder** [bterlson/ecmarkup#126]
Now that [ecma262 issue #960](https://github.com/tc39/ecma262/pull/960) is closed and the `type="example"` attributes added where necessary, need to adjust the `elements.css` to address [ecma262 issue #956](https://github.com/tc39/ecma262/issues/956). It's a matter of changing

```css
emu-production {
    display: block;
    margin-top: 1em;
    margin-bottom: 1em;
    margin-left: 5ex;
}
```

to

```css
emu-production {
    display: block;
}

emu-grammar[type="example"] emu-production {
    margin-top: 1em;
    margin-bottom: 1em;
    margin-left: 5ex;
}
```

But the change needs a lot of verification. I'll make the change, verify no unwanted impacts on ecma262 (or address them if necessary), and do a PR.

I'm not seeing `emu-grammar` or `emu-production` elements in ecma402. Are there other projects we need to ping to ensure they've added any `type="example"` they need...?
