### ISSUE TITLE
Consider adding a space around section numbers (.secnum)

### ISSUE THREAD

**Issue by Ms2ger** [bterlson/ecmarkup#140]
Currently the markup is something like
```html
<h1><span class="secnum">1.1</span>AbstractOp</h1>
```
and spacing between the number is inserted in CSS:
```css
h1 .secnum {
    margin-right: 10px;
}
```

This is somewhat fishy semantically, and means that when I try to select "AbstractOp" by double-clicking on it, I end up selecting "1AbstractOp" instead.
